apiVersion: v1
kind: Service
metadata:
  annotations:
    argocd.argoproj.io/sync-options: Prune=true
  name: sample-app2
spec:
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: sample-app2
